#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install haproxy

sudo apt-get install certbot

sudo certbot certonly --standalone -d www.your_domain.com

sudo nano /etc/haproxy/haproxy.cfg

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.holberton.online/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    server web-server 127.0.0.1:80

sudo service haproxy restart
