#!/usr/bin/env bash
sudo nano /etc/haproxy/haproxy.cfg

frontend www-http
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.your_domain.com/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    server web-server 127.0.0.1:80

sudo service haproxy restart
