#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install -y nginx
echo "<html><head><title>Hello World Page</title></head><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo sed -i 's/\blisten 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Nginx has been installed and configured. It is now listening on port 80."
