#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install -y nginx

custom_header_name="X-Served-By"
server_hostname=$(hostname)

echo "Adding custom header to Nginx configuration..."
sudo bash -c "cat > /etc/nginx/sites-available/default" <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header $custom_header_name $server_hostname;
        # Other Nginx configuration settings
        # ...
    }

    # Additional server blocks and configurations if needed
}
EOF

echo "Testing Nginx configuration..."
sudo nginx -t

if [ $? -eq 0 ]; then
    echo "Restarting Nginx..."
    sudo service nginx restart
else
    echo "Error: Nginx configuration test failed. Please check the configuration."
fi

echo "Configuration completed."
