#!/usr/bin/env bash
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run with sudo or as root."
    exit 1
fi

echo "Installing HAProxy..."
apt-get update
apt-get install -y haproxy

echo "Configuring HAProxy..."

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend main
    bind *:80
    default_backend app

backend app
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

systemctl enable haproxy
systemctl restart haproxy

echo "HAProxy installation and configuration completed."
