#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install -y net-tools

sudo service nginx start

if ! grep -q "listen 80 default_server;" /etc/nginx/sites-available/default; then
    sudo sed -i '/server_name _;/a \\\tlisten 80 default_server;' /etc/nginx/sites-available/default
fi

sudo service nginx restart

if sudo netstat -tulpn | grep -q ":80"; then
    echo "Nginx is now listening on port 80."
else
    echo "Failed to configure Nginx to listen on port 80."
fi
