#!/usr/bin/env bash
key_name="school"
key_bits=4096

read -s -p "Enter passphrase for the key: " passphrase
echo

ssh-keygen -t rsa -b $key_bits -f ~/.ssh/$key_name -N "$passphrase"

echo "RSA key pair created successfully."
